version: "3.3"
services:
  consul:
    image: consul:1.7.1
    ports:
      - 8500:8500
    restart: always
  registrator:
    image: gliderlabs/registrator:latest
    command: consul://consul:8500
    restart: always
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul
  pg_primary:
    image: bhuwanupadhyay/postgres-stream-replication-primary
    build:
      context: primary
    ports:
      - 5432
        volumes:
          - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employees_db
      - POSTGRES_REPLICATION_LOGIN_CONNECTION_LIMIT=100
    depends_on:
      - consul
  pg_replica:
    image: bhuwanupadhyay/postgres-stream-replication-replica
    build:
      context: replica
    ports:
      - 5432
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_REPLICAyTION_PRIMARY_HOST=pg_primary
      - POSTGRES_REPLICATION_PRIMARY_PORT=5432
    depends_on:
      - pg_primary
      - consul
    links:
      - pg_primary
volumes:
  pg_data: