version: "3.3"
services:
  pg_primary:
    image: bhuwanupadhyay/postgres-stream-replication-primary
    build:
      context: primary
    ports:
      - 5432
    #    volumes:
    #      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employees_db
      - POSTGRES_REPLICATION_LOGIN_CONNECTION_LIMIT=100
  pg_replica:
    image: bhuwanupadhyay/postgres-stream-replication-replica
    build:
      context: replica
    ports:
      - 5432
    environment:
      - POSTGRES_REPLICATION_USER=repl_user
      - POSTGRES_REPLICATION_PASSWORD=repl_password
      - POSTGRES_REPLICATION_PRIMARY_HOST=pg_primary
      - POSTGRES_REPLICATION_PRIMARY_PORT=5432
    depends_on:
      - pg_primary
    links:
      - pg_primary

#volumes:
#  pg_data: