version: '3'

volumes:
  keycloak_postgres:

networks:
  keycloak:
    external: false

services:
  keycloak-postgres:
    image: 'postgres:9.6.17-alpine'
    environment:
      POSTGRES_DB: ${KC_POSTGRES_DATABASE:-keycloak}
      POSTGRES_USER: ${KC_POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD:-keycloak}
    volumes:
      - 'keycloak_postgres:/var/lib/postgresql/data'
    networks:
      - keycloak
  keycloak:
    image: bhuwanupadhyay/keycloak-custom-theme:latest
    build: ./keycloak
    depends_on:
      - keycloak-postgres
    ports:
      - '9990:9990'
      - '8080:8080'
    volumes:
      - ./config:/keycloak-config
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
#      KEYCLOAK_IMPORT: /keycloak-config/my-realm.json
      DB_VENDOR: ${DB_VENDOR:-postgres}
      DB_ADDR: ${DB_ADDR:-keycloak-postgres}
      DB_USER: ${DB_USER:-keycloak}
      DB_PASSWORD: ${DB_PASSWORD:-keycloak}
    networks:
      - keycloak